package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// A small, fully consistent spec: 6 requirements (one C10-exempt), 8
// tests, and the canonical matrix they generate.

const base01 = `# 01 — Product requirements (fixture)

## Goals

| ID | Goal |
|----|------|
| G1 | Detect agents on decoy vhosts |

## Functional requirements

### P0

| ID | Requirement | Acceptance criteria |
|----|-------------|---------------------|
| FR-01 | Serve decoy pages | 200 with beacon |
| FR-02 | Mint session tokens | unique per session |

### P2 (design for, do not build — exempt from C10 in v1: no v1 tests, no 08 rows)

| ID | Requirement |
|----|-------------|
| FR-17 | Later feature |

## Non-functional requirements

| ID | Requirement | Target |
|----|-------------|--------|
| NFR-01 | Memory ceiling | 60 MB steady state or less |

## Security requirements

| ID | Requirement |
|----|-------------|
| SEC-01 | Bundle verification | Ed25519 signature |
`

const base07 = `# 07 — Test plan (fixture)

## 3. Test cases

### Unit

| ID | Covers | Test |
|----|--------|------|
| T-U-01 | FR-01, SEC-01, C1, C2 | renders and mints |
| T-U-02 | FR-02, C3, C4 | scores |
| T-U-03 | NFR-01, C5, C6, C7 | bounds |
| T-U-04 | C8 | retention |
| T-U-05 | C9 | reference bundle |

### Integration

| ID | Covers | Test |
|----|--------|------|
| T-I-01 | FR-01, G1 | end to end |

### Acceptance

| ID | Covers | Test |
|----|--------|------|
| T-A-01 | FR-02 | band |
| T-A-02 | FR-02, G1 | band |

## 5. Exit criteria per milestone

| Milestone | Must pass |
|-----------|-----------|
| M-1 | T-U-01 |
`

const base08 = `# 08 — Traceability matrix (fixture)

Regenerated by tools/trace; CI fails on any drift.

| Req | Design | Tests |
|-----|--------|-------|
| FR-01 | 02 | T-U-01, T-I-01 |
| FR-02 | 05 | T-U-02, T-A-01..02 |
| NFR-01 | 02 | T-U-03 |
| SEC-01 | 06 | T-U-01 |
| C1 | ADR-001 | T-U-01 |
| C2 | 02 budget | T-U-01 |
| C3 | 02 | T-U-02 |
| C4 | 06 | T-U-02 |
| C5 | 02 | T-U-03 |
| C6 | 05 | T-U-03 |
| C7 | ADR-003 | T-U-03 |
| C8 | 03 | T-U-04 |
| C9 | ADR-006 | T-U-05 |
| C10 | this matrix, tools/trace | — (no T-ID) |

## Goals (PRD)

| Req | Design | Tests |
|-----|--------|-------|
| G1 | 07 harness | T-I-01, T-A-02 |
`

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func readSpec(t *testing.T, dir, name string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

// newSpec writes the base fixture into a temp dir and rotates the stamp.
func newSpec(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	writeFile(t, dir, "01-prd.md", base01)
	writeFile(t, dir, "07-test-plan.md", base07)
	writeFile(t, dir, "08-traceability.md", base08)
	if _, err := runStamp(dir, true); err != nil {
		t.Fatalf("stamp rotate: %v", err)
	}
	return dir
}

// replaceLine rewrites one line of a spec file (delete: newLine = "").
func replaceLine(t *testing.T, dir, file, oldLine, newLine string) {
	t.Helper()
	text := readSpec(t, dir, file)
	if !strings.Contains(text, oldLine) {
		t.Fatalf("%s: line not found: %q", file, oldLine)
	}
	writeFile(t, dir, file, strings.Replace(text, oldLine, newLine, 1))
}

func check(t *testing.T, dir string) []string {
	t.Helper()
	findings, err := runMatrix(dir)
	if err != nil {
		t.Fatalf("runMatrix: %v", err)
	}
	return findings
}

func wantClean(t *testing.T, dir string) {
	t.Helper()
	for _, f := range check(t, dir) {
		t.Errorf("unexpected finding: %s", f)
	}
}

func wantFinding(t *testing.T, dir, sub string) {
	t.Helper()
	findings := check(t, dir)
	for _, f := range findings {
		if strings.Contains(f, sub) {
			return
		}
	}
	t.Errorf("no finding containing %q; got: %v", sub, findings)
}

func TestConsistentBase(t *testing.T) {
	dir := newSpec(t)
	wantClean(t, dir)
	findings, err := runStamp(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range findings {
		t.Errorf("stamp finding: %s", f)
	}
}

func TestMissingRow(t *testing.T) {
	dir := newSpec(t)
	replaceLine(t, dir, "08-traceability.md", "| FR-02 | 05 | T-U-02, T-A-01..02 |", "")
	wantFinding(t, dir, "FR-02 has no row")
}

func TestExtraRow(t *testing.T) {
	dir := newSpec(t)
	replaceLine(t, dir, "08-traceability.md",
		"| FR-01 | 02 | T-U-01, T-I-01 |",
		"| FR-01 | 02 | T-U-01, T-I-01 |\n| FR-99 | stray | T-U-01 |")
	wantFinding(t, dir, "FR-99 matches no requirement in 01")
}

func TestExemptRow(t *testing.T) {
	dir := newSpec(t)
	replaceLine(t, dir, "08-traceability.md",
		"| C1 | ADR-001 | T-U-01 |",
		"| FR-17 | later | — |\n| C1 | ADR-001 | T-U-01 |")
	wantFinding(t, dir, "FR-17 is C10-exempt")
}

func TestDuplicateRow(t *testing.T) {
	dir := newSpec(t)
	replaceLine(t, dir, "08-traceability.md",
		"| C1 | ADR-001 | T-U-01 |",
		"| C1 | ADR-001 | T-U-01 |\n| C1 | ADR-001 | T-U-01 |")
	wantFinding(t, dir, "duplicate row C1")
}

func TestWrongTests(t *testing.T) {
	dir := newSpec(t)
	replaceLine(t, dir, "08-traceability.md",
		"| FR-01 | 02 | T-U-01, T-I-01 |",
		"| FR-01 | 02 | T-U-02 |")
	wantFinding(t, dir, "FR-01 Tests cell disagrees with 07")
}

func TestReorderedCell(t *testing.T) {
	// Same set, wrong order: only the byte-exact re-emit catches it.
	dir := newSpec(t)
	replaceLine(t, dir, "08-traceability.md",
		"| FR-01 | 02 | T-U-01, T-I-01 |",
		"| FR-01 | 02 | T-I-01, T-U-01 |")
	wantFinding(t, dir, "differs from the committed file")
}

func TestRangeMismatch(t *testing.T) {
	dir := newSpec(t)
	replaceLine(t, dir, "08-traceability.md",
		"| FR-02 | 05 | T-U-02, T-A-01..02 |",
		"| FR-02 | 05 | T-U-02, T-A-01..03 |")
	wantFinding(t, dir, "T-A-03") // extra: the range expands past 07
}

func TestNonContiguousRange(t *testing.T) {
	dir := newSpec(t)
	// A covering test declared between the range members.
	replaceLine(t, dir, "07-test-plan.md",
		"| T-A-02 | FR-02, G1 | band |",
		"| T-I-02 | FR-02 | q |\n| T-A-02 | FR-02, G1 | band |")
	wantFinding(t, dir, "not contiguous")
}

func TestZeroTest(t *testing.T) {
	dir := newSpec(t)
	replaceLine(t, dir, "07-test-plan.md",
		"| T-U-03 | NFR-01, C5, C6, C7 | bounds |",
		"| T-U-03 | C5, C6, C7 | bounds |")
	replaceLine(t, dir, "08-traceability.md",
		"| NFR-01 | 02 | T-U-03 |",
		"| NFR-01 | 02 | — |")
	wantFinding(t, dir, "NFR-01 has no tests")
}

func TestOrphanTest(t *testing.T) {
	dir := newSpec(t)
	replaceLine(t, dir, "07-test-plan.md",
		"| T-U-05 | C9 | reference bundle |",
		"| T-U-05 | C9 | reference bundle |\n| T-U-06 | ADR-002, rotation | f |")
	wantFinding(t, dir, "T-U-06 covers no requirement")
}

func TestC10Covered(t *testing.T) {
	dir := newSpec(t)
	replaceLine(t, dir, "07-test-plan.md",
		"| T-U-04 | C8 | retention |",
		"| T-U-04 | C8, C10 | retention |")
	wantFinding(t, dir, "covers C10")
}

func TestC10CellHasTID(t *testing.T) {
	dir := newSpec(t)
	replaceLine(t, dir, "08-traceability.md",
		"| C10 | this matrix, tools/trace | — (no T-ID) |",
		"| C10 | this matrix, tools/trace | T-U-04 |")
	wantFinding(t, dir, "C10 Tests cell contains a T-ID")
}

func TestDuplicateTestID(t *testing.T) {
	dir := newSpec(t)
	replaceLine(t, dir, "07-test-plan.md",
		"| T-U-01 | FR-01, SEC-01, C1, C2 | renders and mints |",
		"| T-U-01 | FR-01, SEC-01, C1, C2 | renders and mints |\n| T-U-01 | FR-01 | dup |")
	wantFinding(t, dir, "duplicate test ID T-U-01")
}

func TestDuplicateReqID(t *testing.T) {
	dir := newSpec(t)
	replaceLine(t, dir, "01-prd.md",
		"| FR-01 | Serve decoy pages | 200 with beacon |",
		"| FR-01 | Serve decoy pages | 200 with beacon |\n| FR-01 | Serve decoy pages | dup |")
	wantFinding(t, dir, "duplicate requirement ID FR-01")
}

func TestMixedTable(t *testing.T) {
	dir := newSpec(t)
	replaceLine(t, dir, "08-traceability.md",
		"| C10 | this matrix, tools/trace | — (no T-ID) |",
		"| C10 | this matrix, tools/trace | — (no T-ID) |\n| G1 | 07 harness | T-I-01, T-A-02 |")
	wantFinding(t, dir, "mixes goal and requirement rows")
}

func TestDuplicateGoalID(t *testing.T) {
	dir := newSpec(t)
	replaceLine(t, dir, "01-prd.md",
		"| G1 | Detect agents on decoy vhosts |",
		"| G1 | Detect agents on decoy vhosts |\n| G1 | dup |")
	wantFinding(t, dir, "duplicate requirement ID G1")
}

func TestCaps(t *testing.T) {
	dir := newSpec(t)
	long := strings.Repeat("x", 9000)
	replaceLine(t, dir, "08-traceability.md",
		"| G1 | 07 harness | T-I-01, T-A-02 |",
		"| G1 | "+long+" | T-I-01, T-A-02 |")
	wantFinding(t, dir, "byte cap")
}

func TestCRLF(t *testing.T) {
	dir := newSpec(t)
	writeFile(t, dir, "08-traceability.md", strings.ReplaceAll(base08, "\n", "\r\n"))
	wantFinding(t, dir, "CRLF")
}

func TestStampMismatch(t *testing.T) {
	dir := newSpec(t)
	writeFile(t, dir, "01-prd.md", base01+"tampered\n")
	findings, err := runStamp(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range findings {
		if strings.Contains(f, `"01-prd.md" changed`) {
			return
		}
	}
	t.Errorf("no change finding; got: %v", findings)
}

func TestStampExtraFile(t *testing.T) {
	dir := newSpec(t)
	writeFile(t, dir, "stray.md", "stray\n")
	findings, err := runStamp(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range findings {
		if strings.Contains(f, `"stray.md" is not stamped`) {
			return
		}
	}
	t.Errorf("no extra-file finding; got: %v", findings)
}

func TestStampMissingFile(t *testing.T) {
	dir := newSpec(t)
	if err := os.Remove(filepath.Join(dir, "08-traceability.md")); err != nil {
		t.Fatal(err)
	}
	findings, err := runStamp(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range findings {
		if strings.Contains(f, `"08-traceability.md" is stamped but missing`) {
			return
		}
	}
	t.Errorf("no missing-file finding; got: %v", findings)
}

func TestUsageAndExitCodes(t *testing.T) {
	if got := run(nil); got != 2 {
		t.Errorf("run(nil): got %d, want 2 (no spec dir)", got)
	}
	if got := run([]string{"bogus"}); got != 2 {
		t.Errorf("unknown mode: got %d, want 2", got)
	}
	if got := run([]string{"matrix", "stamp"}); got != 2 {
		t.Errorf("two non-modes: got %d, want 2", got)
	}
	if got := run([]string{"--write"}); got != 2 {
		t.Errorf("--write in matrix mode: got %d, want 2", got)
	}
	if got := run([]string{"-x"}); got != 2 {
		t.Errorf("unknown flag: got %d, want 2", got)
	}
}

func TestStampEscapesNames(t *testing.T) {
	dir := newSpec(t)
	writeFile(t, dir, "evil\x1b[31m\nname.md", "x\n")
	findings, err := runStamp(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range findings {
		if strings.ContainsAny(f, "\x1b\n") {
			t.Errorf("finding carries a raw control character: %q", f)
		}
	}
	if len(findings) == 0 {
		t.Error("no finding for the unstamped file")
	}
}
